In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('..\\input\\jpx-tokyo-stock-exchange-prediction\\training_price_features.csv')
df.tail(5)

,RowId,Date,SecuritiesCode,Open,High,Low,Close,Volume,AdjustmentFactor,ExpectedDividend,...,ExpMovingAvg_20Day,Volatility_20Day,Return_30Day,MovingAvg_30Day,ExpMovingAvg_30Day,Volatility_30Day,Return_50Day,MovingAvg_50Day,ExpMovingAvg_50Day,Volatility_50Day
1880526,20201224_9997,2020-12-24,9997,995.0,1037.0,995.0,1025.0,332300,1.0,0,...,964.393846,0.027769,0.163451,942.633333,954.598641,0.026044,0.067708,937.98,943.106150,0.034980
1880527,20201225_9997,2020-12-25,9997,1018.0,1072.0,1018.0,1065.0,426200,1.0,0,...,973.975385,0.028869,0.241259,949.533333,961.721310,0.026026,0.134185,940.50,947.886301,0.035197
1880528,20201228_9997,2020-12-28,9997,1080.0,1096.0,1050.0,1072.0,391400,1.0,0,...,983.311062,0.028549,0.227950,956.166667,968.836064,0.025956,0.169029,943.60,952.753504,0.034996
1880529,20201229_9997,2020-12-29,9997,1070.0,1095.0,1061.0,1092.0,199000,1.0,0,...,993.662390,0.028623,0.221477,962.766667,976.782124,0.025855,0.176724,946.88,958.214151,0.035042
1880530,20201230_9997,2020-12-30,9997,1092.0,1140.0,1076.0,1134.0,338900,1.0,0,...,1007.027876,0.028294,0.240700,970.100000,986.925213,0.026329,0.193684,950.56,965.107714,0.035268

In [5]:
df['Date'] = pd.to_datetime(df['Date'])
df['data_in_range'] = df['Date'].between('2020-12-01', '2020-12-31')
df_new = df.groupby('SecuritiesCode')['data_in_range'].sum().reset_index(name='counts')
df_new.describe()

       SecuritiesCode       counts
count     2000.000000  2000.000000
mean      5883.054000    21.941000
std       2390.405164     0.886517
min       1301.000000     6.000000
25%       3915.750000    22.000000
50%       6200.500000    22.000000
75%       7938.250000    22.000000
max       9997.000000    22.000000

In [7]:
print(df_new[df_new['counts'] ==22]['SecuritiesCode'].values)

[1301 1332 1333 ... 9993 9994 9997]